{{- if .Values.backend.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "strata-btc-bridge.backend.serviceAccountName" . }}
  labels:
    {{- include "strata-btc-bridge.backend.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.backend.serviceAccount.automountToken }}
{{- end }}
