# Default values for plasma-indexer.
# This is a YAML-formatted file.

# The overall system your service is a part of
system: plasma-indexer
# The name of your service
service: plasma-indexer
# The major version number for your service
version: 1

# Docker settings
image:
  # The name of your docker container
  repository: stratalab/plasma-indexer
  # Your docker container's tag
  tag: ""
  imagePullPolicy: Always 

env:
  - name: _JAVA_OPTIONS
    value: "-Xmx1g -Xms1g -Dstorage.diskCache.bufferSize=2000 -XX:ActiveProcessorCount=4 -XX:+AlwaysPreTouch"

nodeSelector:
  []
  # node_pool: guaranteed-pool
# Istio uses the service account name as a component of the service's security
# identity. Set "create" to false to use a previously created service account.
serviceAccount:
  name: plasma-indexer
  create: true
  automountToken: false

# The initial number of pod replicas to run for your service
replicaCount: 1
# The maximum number of pods from that set that can be unavailable at once
maxUnavailable: 1

# Horizontal pod autoscaler configuration (optional)
# autoscaling:
#   minReplicas: 2
#   maxReplicas: 4
#   targetAverageCpuUtilization: 80

serviceType: ClusterIP

# Port settings
# Ports must be named <protocol>[-<suffix>] to work with Istio.
# Valid protocols are grpc, http, http2, https, mongo, mysql, redis, tcp, tls, udp
ports:
  - name: grpc 
    port: 9084
    targetPort: 9084

# Resource settings (use Kubernetes syntax)
# Optional
resources:
  requests:
    memory: "4Gi"
    cpu: "10m"
  limits:
    memory: "4Gi"
    ephemeral-storage: "500Mi"

podSecurityContext:
  runAsUser: 1001 # TODO: Update plasma-indexer Docker container to use high UID. Add CKV_K8S_40 as a check.
  runAsGroup: 0
  fsGroup: 0
  seccompProfile:
    type: RuntimeDefault

securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

networkPolicy:
  enabled: true

# Probe settings (use Kubernetes syntax)
# Optional
probes:
  startupProbe: # Wait failureThreshold * periodSeconds (300s) before allowing other probes to start.
    grpc:
      port: 9084
    failureThreshold: 30
    timeoutSeconds: 20
  readinessProbe:
    timeoutSeconds: 20
    grpc:
      port: 9084
  # livenessProbe:
  #   initialDelaySeconds: 30
  #   terminationGracePeriodSeconds: 60
  #   timeoutSeconds: 20
  #   grpc:
  #     port: 9084

volume:
  # GKE specific storage classes: standard, standard-rwo, premium-rwo
  storageClass:
  storageSize: 10Gi

# Configuration of an _external_ strata-node Node
nodeRpc:
  host: "localhost"
  port: 9084
  tls: false

replicator:
  enable: true

database:
  existingSecret: ""

